// Package multipart implements MIME multipart parsing, as defined in RFC
// 2046.
//
// The implementation is sufficient for HTTP (RFC 2388) and the multipart
// bodies generated by popular browsers.
package multipart
